### ISSUE TITLE
Release cadence incorrect

### ISSUE THREAD

**Issue by kevinharing** [Azure/azure-workload-identity#1019]
**Describe the bug**

In your readme.md you state:

`Currently, Azure Workload Identity releases on a monthly basis, targeting the last week of the month.`

However, there hasn't been a release for 2 months. Besides that, it seems awfully quiet in here regarding open issues. Not to bash you, but I wonder why this product seems to get so little attention from Microsoft.

**Comment by aramase** [comment]
@kevinharing We typically release once a month for security patches but since we use a distroless image there aren't many CVEs. Also, the project is stable and we haven't added new features that warrant a new release now. 

Most of the issues marked as `bug` have been triaged or folks have reached out through other channels, so I'll update them and close them out. If you're looking for help with anything specific, please do let us know!
