### ISSUE TITLE
Does it need to be Mandatory to Add the Label to deployment Pod (azure.workload.identity/use: "true")

### ISSUE THREAD

**Issue by ashishstationcasinos** [Azure/azure-workload-identity#1025]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Can we make AD workload identity solution work without Label for Pod

**Describe alternatives you've considered**

**Additional context**
I have an Deployment running the cluster. We deploy the services using helm. to the exisiting deployment when I add the label (azure.workload.identity/use: "true") to the helm and deploy the service it failing with 

"Error: UPGRADE FAILED: release workloadidentity-mesh-nestjs failed, and has been rolled back due to atomic being set: cannot patch "workloadidentity-mesh-nestjs" with kind Deployment: Deployment.apps "workloadidentity-mesh-nestjs" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"workloadidentity-mesh-nestjs", "app.kubernetes.io/name":"workloadidentity-mesh-nestjs", "azure.workload.identity/use":"true"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable"

how can I solve this issue ? We are doing automation for all services using helm charts.

**Comment by aramase** [comment]
> Can we make AD workload identity solution work without Label for Pod

The label is required because the `mutatingwebhook` is only configure to mutate incoming pods that have the label. This reduces the latency impact of the webhook and prevents workload pods that require the injected environment variables and projected service account token volume from starting in an unexpected state.

https://github.com/Azure/azure-workload-identity/blob/215911a7da639915650a4fabc132186719b5b29f/deploy/azure-wi-webhook.yaml#L254-L256

> "Error: UPGRADE FAILED: release workloadidentity-mesh-nestjs failed, and has been rolled back due to atomic being set: cannot patch "workloadidentity-mesh-nestjs" with kind Deployment: Deployment.apps "workloadidentity-mesh-nestjs" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"workloadidentity-mesh-nestjs", "app.kubernetes.io/name":"workloadidentity-mesh-nestjs", "azure.workload.identity/use":"true"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable"

The selector field is immutable but you should be able to add the label to `spec.template.metadata.labels` and that'll work fine for upgrade.

**Comment by ashishstationcasinos** [comment]
It worked. Thanks
