### ISSUE TITLE
Pod fails to start due to failure in requesting an access token

### ISSUE THREAD

**Issue by Atavan** [Azure/azure-workload-identity#1115]
I am trying to setup azure workload identity for an aks cluster, I'm using the integrated installation instead of the helm installation by adding these arguments when creating the cluster, enable-oidc-issuer and enable-workload-identity. I've also created a managed identity for the micro service that is being deployed and have created a federated credentials configuration for it.

I've add the necessary changes as outlined by the [documentation](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster) to update the service account to use this annotation:
azure.workload.identity/client-id

And the pod to use this label:
azure.workload.identity/use: "true"

When I deploy the pod to the cluster it fails to start and errors with this message:
```
Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/<tenantid>. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/<tenantid>. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: BadRequest, Response: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}
```
I am not sure what needs to be done to specify the clientid since it is already being set in the service account when deploying.

- Kubernetes version (use `kubectl version`): 1.25.6
- Cloud provider or hardware configuration: Azure

I'm trying to get this working with one pod at the moment but the plan is to have multiple pods for other services with each one having its own managed identity.

**Comment by simonvane** [comment]
Did you manage to resolve this @Atavan? I'm having a similar problem.

**Comment by Atavan** [comment]
@simonvane Sorry I had forgotten to update this issue, I didn't actually solve it, but the issue was in the application. It turned out the application was defaulting to using default azure managed identity credentials and not using the federated credentials that were setup for workload identity. I believe the application was updated to use the WorkloadIdentityCredential class directly. Enabling the workload identity through az cli and setting up the federated identity was done correctly and wasn't the cause of the issue.

**Comment by simonvane** [comment]
Thanks for taking the time to update @Atavan!

I had two symptoms...
- 503s returned by endpoints like http://169.254.169.254/metadata/identity/oauth2/token?resource=https://servicebus.azure.net/&api-version=2018-02-01
- Errors in k8s pods like `Connection String: [No connection string specified], Resource: https://servicebus.azure.net/, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. MSI ResponseCode: ServiceUnavailable, Response: getting assigned identities for pod <my namespace name>/<my pod name> in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors`

Both were resolved by upgrading libraries (e.g. Azure Service Bus SDKs) and using the Azure Identity client library (.NET) with  `DefaultAzureCredential` (which tries `WorkloadIdentityCredential`) rather than legacy authentication methods.

https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet#azure-identity-client-libraries
https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet
