### ISSUE TITLE
Update MSAL GO example to use long term supported SDK

### ISSUE THREAD

**Issue by jeffpuckett** [Azure/azure-workload-identity#622]
**Describe the bug**
The MSAL GO example uses autorest which is not supported after March 2023. Update the sample to something that will be supported long term.

**Steps To Reproduce**

**Expected behavior**
Example using library that will be supported long term.

**Logs**

**Environment**

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by aramase** [comment]
For long term, please refer to the azure identity examples: https://github.com/Azure/azure-workload-identity/tree/main/examples/azure-identity.

**Comment by jeffpuckett** [comment]
This is not complete. The link provided does not offer examples for GO.

**Comment by aramase** [comment]
> This is not complete. The link provided does not offer examples for GO.

@jeffpuckett The GO sdk support is still in beta which is why we haven't published it yet. When `v1.2.0` of azure identity is released, we'll add that example. The MSAL examples were added earlier because azure identity still didn't support client assertion. The SDK team recommendation is to use azure identity instead of MSAL. If you're interested in trying out the go example, this is what they have so far: https://github.com/Azure/azure-sdk-for-go/issues/15615#issuecomment-1211012677.

The intent was not to mark it completed but to say we'll update when the official release is available. For now there is no official release for the azidentity go SDK yet. Here is an issue to track adding that: https://github.com/Azure/azure-workload-identity/issues/187
