### ISSUE TITLE
Unknown error code 50166

### ISSUE THREAD

**Issue by sdebruyn** [Azure/azure-workload-identity#642]
**Describe the bug**

Occasionally a pod fails to retrieve a token with the following error. The error is undocumented so we have no idea what to do resolve this.

**Steps To Reproduce**

Request a token using `DefaultAzureCredential` with the azure-identity Python SDK version 1.11.0

**Expected behavior**

Error should be mentioned in troubleshooting with some guidance on how to resolve this.

**Logs**

```json
{
    "error": "invalid_request",
    "error_description": "AADSTS50166: Request to External OIDC endpoint failed.\r\nTrace ID: ce5b401b-7beb-4757-81ed-7d476f5a1300\r\nCorrelation ID: cb69fd74-8049-4507-a6af-694c53b7af86\r\nTimestamp: 2022-11-16 12:01:14Z",
    "error_codes": [
        50166
    ],
    "timestamp": "2022-11-16 12:01:14Z",
    "trace_id": "ce5b401b-7beb-4757-81ed-7d476f5a1300",
    "correlation_id": "cb69fd74-8049-4507-a6af-694c53b7af86"
}
```

**Environment**

- Kubernetes version (use `kubectl version`): 1.22.11
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): Debian 11 bullseye
- Kernel (e.g. `uname -a`): `5.4.0-1089-azure #94~18.04.1-Ubuntu SMP Fri Aug 5 12:34:50 UTC 2022 x86_64 GNU/Linux`
- Install tools: Python azure-identity 1.11.0 with Python 3.10.8

**Comment by aramase** [comment]
@sdebruyn These errors typically are documented in the AAD docs but since it hasn't been documented yet, we added it to the troubleshooting guide in this project: https://azure.github.io/azure-workload-identity/docs/troubleshooting.html#aadsts90061-request-to-external-oidc-endpoint-failed. Please refer to those docs. 

ref to previous issue: https://github.com/Azure/azure-workload-identity/issues/605. I would recommend opening an issue for the doc here: https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes, so the AAD team can track and include these error codes as part of their documentation.

cc @udayxhegde

**Comment by sdebruyn** [comment]
@aramase Thank you! In this case it seems to be an underlying Azure AD error. The repo says this solution is not supported by Microsoft, but the error is not something I can troubleshoot myself since it's somewhere behind the scenes in AKS or AAD. What would I do in this case? Open an Azure support ticket?

**Comment by aramase** [comment]
> @aramase Thank you! In this case it seems to be an underlying Azure AD error. The repo says this solution is not supported by Microsoft, but the error is not something I can troubleshoot myself since it's somewhere behind the scenes in AKS or AAD. What would I do in this case? Open an Azure support ticket?

@sdebruyn For AAD errors, you can open a support ticket.

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/azure-workload-identity/issues/642#issuecomment-1320324124.
