### ISSUE TITLE
Was alpha rolled out to aks ?

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [Azure/azure-workload-identity#751]
**Describe the bug**
At the same time as [v1.0.0-alpha.0](https://github.com/Azure/azure-workload-identity/releases/tag/v1.0.0-alpha.0) was released my pods starting failing with `azure.identity._exceptions.CredentialUnavailableError: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.` from the Python SDK. I have made no changes to the cluster, the identity or anything in that sort. Have it been auto rolled out? 

**Steps To Reproduce**
Have a AKS cluster running before yesterday where everything was working.

**Expected behavior**
Still work..

**Logs**

**Environment**
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.22.15

**Additional context**

**Comment by thomasfrederikhoeck** [comment]
After adding adding `azure.workload.identity/use: "true"` as described here it fixed it https://dev.azure.com/DSN-AADS/Applications/_build/results?buildId=16332&view=results which was also the breaking feature described in the release. So it looks like the alpha is what is running on AKS now.

**Comment by pinkfloydx33** [comment]
Yeah, same thing happened to us.

**Comment by aramase** [comment]
Hello 👋🏻   thanks for opening the issue.

AKS is rolling out `v0.15.0` in all the regions with the webhook failure policy set to `Fail` instead of `Ignore` and the objectSelector `azure.workload.identity/use: "true"`. AFAIK, AKS sent out an email to all the users currently using WI with AKS add-on. @miwithro to confirm!

**Comment by glloyd2010f** [comment]
> After adding adding `azure.workload.identity/use: "true"` as described here it fixed it https://dev.azure.com/DSN-AADS/Applications/_build/results?buildId=16332&view=results which was also the breaking feature described in the release. So it looks like the alpha is what is running on AKS now.

Can you provide a copy of the fix in this issue? Trying to implement it and I do not have access to the ADO org.

**Comment by pinkfloydx33** [comment]
@glloyd2010f I don't have access either, but the "issue" is that target `Pods` now require a label in addition to the one required on the `ServiceAccount`. The fix is to add the `azure.workload.identity/use: "true"` label to your `Pod` spec. 

Assuming you're using a `Deployment`, you'd make the following update (with irrelevant properties elided):

```yaml
kind: Deployment
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: 'true'
```

**Comment by thomasfrederikhoeck** [comment]
@glloyd2010f wrong link. I meant this https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#pod-labels
